[package]
name = "user_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix = "0.13.0"
chrono = "0.4.23"
diesel = { version = "2.0.3", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
