version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env.dev
volumes:
  postgres_data: