version: "3.8"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env.dev.test
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    ports:
      - "5434:5434"
    volumes:
      - ./data/postgres_test:/var/lib/postgresql/data/
    env_file:
      - .env.dev.test
volumes:
  postgres_data: